### ISSUE TITLE
Group Daily Quests don't reset

### ISSUE THREAD

**Issue by Dalethium** [awinterstein/habitica#2]
The daily quests within groups don't seem to reset. I'm new to this software, so I may be not using it correctly, but they don't seem to be resetting. I waited 2 days.

If you need more info, please let me know!

I really don't know if this is something caused by this fork or upstream, but I thought I'd report it here first.

**Comment by awinterstein** [comment]
This is a known limitation of this fork, also described in the readme file: https://github.com/awinterstein/habitica?tab=readme-ov-file#limitations ("dailies for group plans are not reset (the actual cron script [team-cron.js](https://github.com/awinterstein/habitica/blob/self-host/scripts/team-cron.js) would need to be executed regularly for this").

With my extremely limited JavaScript knowledge, I did not manage to figure out how to execute this script file. If you or someone else knows how do to this, I would be very happy to integrate it with the Docker container.

**Comment by Dalethium** [comment]
I'll see what I can do!

**Comment by Saik0Shinigami** [comment]
There's no references to the methods in other files on the repo... or in the original repo. It's possible that they actually have an hourly cron that runs something but I couldn't get it to actuate at all after a hour or so of tinkering with it (without changing the code itself).

There are pull requests that makes it seem like it's not implemented at all https://github.com/HabitRPG/habitica/pull/12219, though I'd doubt that... but I don't have a habitica account nor a group to test with on the live service.

Shabitica doesn't show anything relevant either from what I can tell.

**Comment by awinterstein** [comment]
The main reason why I think that the team-cron.js needs to be called externally as a cron on the server is that it was added to the repository with the commit message "draft of server literal-actual-cron script". And I didn't find anything else in the Habitica source code that would reset the dailies of a team. For example, I couldn't find any API call that would do that.

In Shabitica you won't find anything regarding it, because Shabitica was only updated a long time ago. As far as I know, teams were only introduced to Habitica later.

**Comment by Saik0Shinigami** [comment]
I've gotten *somewhere* with this... though not sure how far along the path I am. 

The version of node in the container doesn't like the team-cron.js file being run directly. A transpiler script is possible as habitica has @babel/register available. 

```
require('@babel/register')({
  extensions: ['.js'],
  presets: ['@babel/preset-env'],
});
require('./scripts/team-cron.js');
```

Then running it with 

`node ./run-team-cron.js`

I put the script at the  root of habitica `/var/lib/habitica`. It does a lot of thinking then eventually complains about something being undefined in `website/server/libs/encryption.js:11:20`

```
root@61409d59d7bc:/var/lib/habitica# cat website/server/libs/encryption.js 
import {
  createCipheriv,
  createDecipheriv,
} from 'crypto';
import nconf from 'nconf';

const algorithm = 'aes-256-ctr';
const SESSION_SECRET_KEY = nconf.get('SESSION_SECRET_KEY');
const SESSION_SECRET_IV = nconf.get('SESSION_SECRET_IV');

const key = Buffer.from(SESSION_SECRET_KEY, 'hex');
const iv = Buffer.from(SESSION_SECRET_IV, 'hex');

export function encrypt (text) {
  const cipher = createCipheriv(algorithm, key, iv);
  let crypted = cipher.update(text, 'utf8', 'hex');
  crypted += cipher.final('hex');
  return crypted;
}

export function decrypt (text) {
  const decipher = createDecipheriv(algorithm, key, iv);
  let dec = decipher.update(text, 'hex', 'utf8');
  dec += decipher.final('utf8');
  return dec;
}
```

I believe that my stub file could work if 
```
const key = Buffer.from(SESSION_SECRET_KEY, 'hex');
const iv = Buffer.from(SESSION_SECRET_IV, 'hex');
```

were set... I'll do more testing later. My work day starts soon.

**Comment by prabhjotsbhatia-ca** [comment]
I tried your suggestion and set 
```
const nconf = require("nconf");

// Load environment variables first
nconf.argv().env();

// Set defaults if not found in environment
nconf.defaults({
  SESSION_SECRET_KEY:
    "1234567891234567891234567891234567891234567891234567891234567891",
  SESSION_SECRET_IV: "12345678912345678912345678912345",
});

require("@babel/register")({
  extensions: [".js"],
  presets: ["@babel/preset-env"],
});
require("./scripts/team-cron.js");
```

and it overcame the encryption.js error. 
But then it led to this error below. (Looks like a mongodb connection error, will test)

<details><summary>Error</summary>
<p>


```
2025-01-02T20:47:28.596Z - error MongooseError: Operation `newsposts.findOne()` buffering timed out after 10000ms
    at Timeout.<anonymous> (/var/lib/habitica/node_modules/mongoose/lib/drivers/node-mongodb-native/collection.js:185:23)
    at listOnTimeout (node:internal/timers:581:17)
    at processTimers (node:internal/timers:519:7)
{
  fullError: MongooseError: Operation `newsposts.findOne()` buffering timed out after 10000ms
      at Timeout.<anonymous> (/var/lib/habitica/node_modules/mongoose/lib/drivers/node-mongodb-native/collection.js:185:23)
      at listOnTimeout (node:internal/timers:581:17)
      at processTimers (node:internal/timers:519:7),
  level: 'error',
  message: 'MongooseError: Operation `newsposts.findOne()` buffering timed out after 10000ms'
}
2025-01-02T20:47:28.600Z - error MongooseError: Operation `users.find()` buffering timed out after 10000ms
    at Timeout.<anonymous> (/var/lib/habitica/node_modules/mongoose/lib/drivers/node-mongodb-native/collection.js:185:23)
    at listOnTimeout (node:internal/timers:581:17)
    at processTimers (node:internal/timers:519:7)
{
  fullError: MongooseError: Operation `users.find()` buffering timed out after 10000ms
      at Timeout.<anonymous> (/var/lib/habitica/node_modules/mongoose/lib/drivers/node-mongodb-native/collection.js:185:23)
      at listOnTimeout (node:internal/timers:581:17)
      at processTimers (node:internal/timers:519:7),
  level: 'error',
  message: 'MongooseError: Operation `users.find()` buffering timed out after 10000ms'
}
2025-01-02T20:47:28.601Z - error MongooseError: Operation `groups.countDocuments()` buffering timed out after 10000ms
    at Timeout.<anonymous> (/var/lib/habitica/node_modules/mongoose/lib/drivers/node-mongodb-native/collection.js:185:23)
    at listOnTimeout (node:internal/timers:581:17)
    at processTimers (node:internal/timers:519:7) unhandledPromiseRejection
{
  message: 'MongooseError: Operation `groups.countDocuments()` buffering timed out after 10000ms',
  promise: Promise {
    <rejected> MongooseError: Operation `groups.countDocuments()` buffering timed out after 10000ms
        at Timeout.<anonymous> (/var/lib/habitica/node_modules/mongoose/lib/drivers/node-mongodb-native/collection.js:185:23)
        at listOnTimeout (node:internal/timers:581:17)
        at processTimers (node:internal/timers:519:7)
  },
  fullError: MongooseError: Operation `groups.countDocuments()` buffering timed out after 10000ms
      at Timeout.<anonymous> (/var/lib/habitica/node_modules/mongoose/lib/drivers/node-mongodb-native/collection.js:185:23)
      at listOnTimeout (node:internal/timers:581:17)
      at processTimers (node:internal/timers:519:7),
  level: 'error'
}
2025-01-02T20:47:28.602Z - error MongooseError: Operation `groups.findOne()` buffering timed out after 10000ms
    at Timeout.<anonymous> (/var/lib/habitica/node_modules/mongoose/lib/drivers/node-mongodb-native/collection.js:185:23)
    at listOnTimeout (node:internal/timers:581:17)
    at processTimers (node:internal/timers:519:7) unhandledPromiseRejection
{
  message: 'MongooseError: Operation `groups.findOne()` buffering timed out after 10000ms',
  promise: Promise {
    <rejected> MongooseError: Operation `groups.findOne()` buffering timed out after 10000ms
        at Timeout.<anonymous> (/var/lib/habitica/node_modules/mongoose/lib/drivers/node-mongodb-native/collection.js:185:23)
        at listOnTimeout (node:internal/timers:581:17)
        at processTimers (node:internal/timers:519:7)
  },
  fullError: MongooseError: Operation `groups.findOne()` buffering timed out after 10000ms
      at Timeout.<anonymous> (/var/lib/habitica/node_modules/mongoose/lib/drivers/node-mongodb-native/collection.js:185:23)
      at listOnTimeout (node:internal/timers:581:17)
      at processTimers (node:internal/timers:519:7),
  level: 'error'
}
```


</p>
</details>

**Comment by Saik0Shinigami** [comment]
Did you init a new instance with those keys?

I would suspect that you can't call the data back with the keys if they were put in place with "null" keys.

I would further suspect that we would need to support setting these keys in the docker-compose for the init of the whole instance to make this work properly.

**Comment by prabhjotsbhatia-ca** [comment]
well I got those keys from `/var/lib/habitica/config.json`.  Kinda out of my depth here.

**Comment by prabhjotsbhatia-ca** [comment]
Okay, I was able to figure it. 
The team-cron.js needs to be modified:  (Needs to live in /var/lib/habitica/scripts)

````
@@ -107,7 +107,7 @@
   return Promise.all(toSave);
 }
 
-export default async function processTeamsCron() {
+module.exports = async function processTeamsCron() {
   const activeTeams = await Group.find({
     "purchased.plan.customerId": { $exists: true },
     $or: [
@@ -119,4 +119,4 @@
 
   const cronPromises = activeTeams.map(updateTeamTasks);
   return Promise.all(cronPromises);
-}
+};
````

and here's the run-team-cron.js:  (/var/lib/habitica)

```
const mongoose = require("mongoose");
const nconf = require("nconf");

// Load config first
// nconf.file("config.json");

nconf.argv().env();

// Set defaults if not found in environment
nconf.defaults({
  SESSION_SECRET_KEY:
    "1234567891234567891234567891234567891234567891234567891234567891",
  SESSION_SECRET_IV: "12345678912345678912345678912345",
});

async function main() {
  try {
    // Connect to MongoDB and wait for connection (Not sure if this is really necessary)
    await mongoose.connect("mongodb://root-mongo-1:27017/habitica", {
      useNewUrlParser: true,
      useUnifiedTopology: true,
    });

    console.log("Connected to MongoDB");


    // Register babel after MongoDB connection
    require("@babel/register")({
      extensions: [".js"],
      presets: ["@babel/preset-env"],
      cache: false,
    });

    console.log("Babel registered");

    const processTeamsCron = require("./scripts/team-cron.js");

    if (typeof processTeamsCron !== "function") {
      throw new Error("processTeamsCron is not properly exported");
    }

    // Run the cron job
    console.log("Starting team cron processing...");
    await processTeamsCron();
    console.log("Team cron processing completed");
    await mongoose.connection.close();
    process.exit(0);
  } catch (error) {
    console.error("Error:", error);
    if (mongoose.connection) {
      await mongoose.connection.close();
    }
    process.exit(1);
  }
}

main().catch(console.error);

```

and to execute it, run

```
cd /var/lib/habitica && node run-team-cron.js
```

**Comment by awinterstein** [comment]
I executed this and it did actually reset the team dailies - great!

What would be the best way to regularly run this with the container setup? Could it be integrated with the server container or do we need an additional container that runs this script?

**Comment by Saik0Shinigami** [comment]
Would probably be safe to install cronie or crond in the container and use something like the following... Considering that there is some options for timezones in the app, running the cron every hour should capture that I think? I dunno I'd want to test if hourly is right, or if it is really daily. 

It wouldn't make sense to me personally to have a second container handling it.

Add to dockerfile, probably towards the end:
`RUN apt-get update && apt-get -y install cron`
`COPY habiticateamcron /etc/cron.d/habiticateamcron`
`RUN chmod 0644 /etc/cron.d/habiticateamcron`
`RUN crontab /etc/cron.d/habiticateamcron`


Contents of `habiticateamcron` assuming that prabhjotsbhatia-ca's stuff is correct (I haven't tested it yet, and probably wont have time today to do so)
`0 * * * * cd /var/lib/habitica && /usr/local/bin/node ./run-team-cron.js`


The scripts folder will need to be imported on container creation as well in the dockerfile.
`COPY --from=build /usr/src/habitica/scripts /var/lib/habitica/scripts/`

**Comment by prabhjotsbhatia-ca** [comment]
I think it should be once daily, considering it would also hit the health negatively if the task isn't finished. As I understand habitica runs cron only when the user checks-in at the start of their day. At least that's how extensions like [Auto-cron](https://habitica.fandom.com/wiki/Auto_Cron) portray it. 

Also, I'm sure the run-team-cron.js can be further optimized by someone more knowledgeable than me, like @Saik0Shinigami, perhaps even combining them into a single script.

**Comment by Saik0Shinigami** [comment]
I doubt I'm any better than anyone when it comes to Javascript... I just know enough to cause trouble and debug some stuff. 

My thought on the hourly was that teams have a "day start" that can be set.
![image](https://github.com/user-attachments/assets/b7aac5b0-914b-452f-9aa1-32124deccdb7)

If the "day start" is 4am, but the cron only runs once a day at midnight let's say... then how does the 4am get captured in that case? That's why I thought hourly. But I could be wrong. And ultimately the fastest way to know for sure would simply be to test it.

Edit: That link also seems to suggest something similar... That an internal script will setup the cron to do stuff. I think *both* might need to run in order to do something? Maybe? Once again easiest way to tell would simple be to run it.

>If you have [cron](https://habitica.fandom.com/wiki/Cron) before the script has run, the script will not do anything.

But this could also just be something else entirely...

**Comment by prabhjotsbhatia-ca** [comment]
You're right. I tested it out. Doesn't seem to do anything after the first run. 

The script also has a check to ensure it only gets run if the last team cron was over 1 day ago. 

>
> (line 27)    `daysSince(team.cron.lastProcessed, teamLeader.preferences) > 0`
>   


Also, I suggest running it at a different minute of the hour, since habitica has whole hour increments for custom day start (like 4.00 AM, 5.00 AM etc). Here's running it at minute 2 (so 4.02 AM, 5.02 AM etc) Perhaps we could also add a log to the `habiticateamcron` file so that it doesn't just silently fail: 

```
2 * * * * cd /var/lib/habitica && /usr/local/bin/node ./run-team-cron.js >> /var/log/cron.log 2>&1
```

**Comment by d3vsec** [comment]
Dear all,

first of all, thanks for all your affort to fix this. I currenty run a local docker setup and wanted to try your workaround.
Unfortunately I am getting the following error and I am wondering why:
`
root@habitica:/usr/src/habitica/scripts# node run-team-cron.js 
Connected to MongoDB
Babel registered
Error: /usr/src/habitica/website/server/models/group.js:1
import moment from 'moment';
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at wrapSafe (node:internal/modules/cjs/loader:1378:20)
    at Module._compile (node:internal/modules/cjs/loader:1428:41)
    at Module._compile (/usr/src/habitica/node_modules/pirates/lib/index.js:117:24)
    at Module._extensions..js (node:internal/modules/cjs/loader:1548:10)
    at Object.newLoader [as .js] (/usr/src/habitica/node_modules/pirates/lib/index.js:121:7)
    at Module.load (node:internal/modules/cjs/loader:1288:32)
    at Function.Module._load (node:internal/modules/cjs/loader:1104:12)
    at Module.require (node:internal/modules/cjs/loader:1311:19)
    at require (node:internal/modules/helpers:179:18)
    at Object.<anonymous> (/usr/src/habitica/scripts/team-cron.js:2:1)
    at Module._compile (node:internal/modules/cjs/loader:1469:14)
    at Module._compile (/usr/src/habitica/node_modules/pirates/lib/index.js:117:24)
    at Module._extensions..js (node:internal/modules/cjs/loader:1548:10)
    at Object.newLoader [as .js] (/usr/src/habitica/node_modules/pirates/lib/index.js:121:7)
    at Module.load (node:internal/modules/cjs/loader:1288:32)
    at Function.Module._load (node:internal/modules/cjs/loader:1104:12)
    at Module.require (node:internal/modules/cjs/loader:1311:19)
    at require (node:internal/modules/helpers:179:18)
    at main (/usr/src/habitica/scripts/run-team-cron.js:35:30)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
`

Sorry to bother you, but I am not a real developer. Maybe you have some suggestion, what I could check?

Thanks in advance!

Wish you a great year 2025.

greets

**Comment by Saik0Shinigami** [comment]
@d3vsec I think we're close to having the full fix in the main branch...  You might just want to wait.

@prabhjotsbhatia-ca  Looking at your PR, that's looks about right to me for the stuff that I know of. 

If @awinterstein merges, I can spin up a copy to test myself as well. Along with validating issue #4 SMTP changes. And double check the other issues that are still open as a data-point that they're all working now.

Than I can finally trick the kids into doing chores...

**Comment by prabhjotsbhatia-ca** [comment]
@d3vsec As @Saik0Shinigami pointed out, better to wait if you're not sure, as the solution has multiple manual steps right now and it won't work unless everything is in place correctly. 

> first of all, thanks for all your affort to fix this. I currenty run a local docker setup and wanted to try your workaround. Unfortunately I am getting the following error and I am wondering why: ` root@habitica:/usr/src/habitica/scripts# node run-team-cron.js 

If you have your own dockerfile, you might want to look at the open PR linked above.
 
I see you're running the run-team-cron.js script from /usr/src/habitica/scripts whereas it needs to be first copied over to /var/lib/habitica/ inside the docker container, along with the *modified* team-cron.js script which needs to be copied over to /var/lib/habitica/scripts/. Then, you need to cd to /var/lib/habitica and execute `node run-team-cron.js`. 
Hope this helps and let us know how that works out for you.

**Comment by awinterstein** [comment]
I merged it and the changes are available now in release 5.32.4.

**Comment by prabhjotsbhatia-ca** [comment]
Interesting error: The scheduled cron fails for some reason but running the actual script works fine. 

```shell
root@022a76ff6d7b:/# cat /var/log/cron.log
Error: MongooseError: The `uri` parameter to `openUri()` must be a string, got "undefined". Make sure the first parameter to `mongoose.connect()` or `mongoose.createConnection()` is a string.
    at NativeConnection.createClient (/var/lib/habitica/node_modules/mongoose/lib/drivers/node-mongodb-native/connection.js:206:11)
    at NativeConnection.openUri (/var/lib/habitica/node_modules/mongoose/lib/connection.js:766:34)
    at Mongoose.connect (/var/lib/habitica/node_modules/mongoose/lib/index.js:416:15)
    at main (/var/lib/habitica/run-team-cron.js:25:20)
    at Object.<anonymous> (/var/lib/habitica/run-team-cron.js:64:1)
    at Module._compile (node:internal/modules/cjs/loader:1469:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1548:10)
    at Module.load (node:internal/modules/cjs/loader:1288:32)
    at Module._load (node:internal/modules/cjs/loader:1104:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:173:12)
root@022a76ff6d7b:/# crontab -l
2 * * * * cd /var/lib/habitica && /usr/local/bin/node ./run-team-cron.js >> /var/log/cron.log 2>&1
root@022a76ff6d7b:/# cd /var/lib/habitica/
root@022a76ff6d7b:/var/lib/habitica# node run-team-cron.js 
Connected to MongoDB
Babel registered
Starting team cron processing...
Team cron processing completed

```

Anybody else seeing this same error?

**Comment by Saik0Shinigami** [comment]
Hah... I was just debugging this. Yes I get the same issue. No connection through cron, but it runs normally.

Seems it has to do with the ENV being available during the Cron task itself.

Normally you'd export in the cron to do it.

So in our case the cron would need to change from 

`cd /var/lib/habitica && /usr/local/bin/node ./run-team-cron.js >> /var/log/cron.log 2>&1`
to 
`export NODE_DB_URI=mongodb://mongo/habitica; cd /var/lib/habitica && /usr/local/bin/node ./run-team-cron.js >> /var/log/cron.log 2>&1`

I'm in the middle of testing it myself. waiting for next hour cycle.

**Comment by prabhjotsbhatia-ca** [comment]
@Saik0Shinigami Cool! I'm going to test that.  For testing, I just change the crontab to `*/2 * * * *` instead of `2 * * * *` to run it every 2 minutes instead of every hour at minute 2.

**Comment by Saik0Shinigami** [comment]
@prabhjotsbhatia-ca  Yeah just didn't get around to it. Was waiting because I should honestly be doing other work. So tweak/context switch back the "the real job that pays me" and come back an hour later...

But then at this rate you'll likely come to an answer before I do. 

A better answer would likely be set
`NODE_DB_URI=$NODE_DB_URI`

At the top of the cron script outright. That way we pull the ENV that is set in the docker compose/run command rather than hard coding it to the local mongo instance. But I was only testing slowly.


Edit: also a secondary safety measure could be to have a default value for the local mongo instance in the .js file, just in case someone doesn't set the URI properly, or at all in the docker run or compose. I'm not sure if it would be needed as I'm sure the URI is used elsewhere plenty... but easy to put in, and wouldn't harm anything otherwise.

`const dbUri = nconf.get("NODE_DB_URI") || "mongodb://mongo/habitica";` in the run-team-cron.js file

Edit2:
And a check as well

```
if (!dbUri) {
  throw new Error("NODE_DB_URI is not set. Please define it in the environment.");
}
```
Probably wouldn't hurt...

**Comment by prabhjotsbhatia-ca** [comment]
Different error now but same effect. doesn't work in cron, but works directly. So curious

```shell
root@022a76ff6d7b:/var/lib/habitica# crontab -l
*/2 * * * * export NODE_DB_URI=$NODE_DB_URI; cd /var/lib/habitica && /usr/local/bin/node ./run-team-cron.js >> /var/log/cron.log 2>&1
root@022a76ff6d7b:/var/lib/habitica# export NODE_DB_URI=$NODE_DB_URI; cd /var/lib/habitica && /usr/local/bin/node ./run-team-cron.js >> /var/log/cron.log 2>&1
root@022a76ff6d7b:/var/lib/habitica# cat /var/log/cron.log 
Connected to MongoDB
Babel registered
Starting team cron processing...
Team cron processing completed
```
2 minutes later: 

```shell
root@022a76ff6d7b:/var/lib/habitica# cat /var/log/cron.log 
Connected to MongoDB
Babel registered
Starting team cron processing...
Team cron processing completed
Error: MongoParseError: Invalid scheme, expected connection string to start with "mongodb://" or "mongodb+srv://"
    at new ConnectionString (/var/lib/habitica/node_modules/mongodb-connection-string-url/lib/index.js:86:19)
    at parseOptions (/var/lib/habitica/node_modules/mongoose/node_modules/mongodb/lib/connection_string.js:191:17)
    at new MongoClient (/var/lib/habitica/node_modules/mongoose/node_modules/mongodb/lib/mongo_client.js:48:63)
    at NativeConnection.createClient (/var/lib/habitica/node_modules/mongoose/lib/drivers/node-mongodb-native/connection.js:288:14)
    at NativeConnection.openUri (/var/lib/habitica/node_modules/mongoose/lib/connection.js:766:34)
    at Mongoose.connect (/var/lib/habitica/node_modules/mongoose/lib/index.js:416:15)
    at main (/var/lib/habitica/run-team-cron.js:25:20)
    at Object.<anonymous> (/var/lib/habitica/run-team-cron.js:64:1)
    at Module._compile (node:internal/modules/cjs/loader:1469:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1548:10)

root@022a76ff6d7b:/var/lib/habitica# 
```

**Comment by Saik0Shinigami** [comment]
So hour cycle just hit for me. 

`2 * * * * export NODE_DB_URI=mongodb://mongo/habitica;cd /var/lib/habitica && /usr/local/bin/node ./run-team-cron.js >> /var/log/cron.log 2>&1`

DOES work for me. Now to just generalize it to grab the ENV programmatically in case someone sets an external db.

**Comment by Saik0Shinigami** [comment]
Okay, I see the malfunction. Cron doesn't like to grab envs that way... Shame... This is a sideways way to pull in all ENVs (even though we don't need them all for this script) that works for me. @prabhjotsbhatia-ca can you confirm if this works for you as well?

Create `/usr/local/bin/run-team-cron.sh`:
```
#!/bin/bash
# Source container environment
. /etc/environment
# Change directory to the script's location
cd /var/lib/habitica
# Run the Node.js script
/usr/local/bin/node ./run-team-cron.js >> /var/log/cron.log 2>&1
```
Update crontab to call this script:
```
2 * * * * /usr/local/bin/run-team-cron.sh
```


Edit: Sorry! forgot to add the /etc/environment part...

`printenv | grep -v "no_proxy" >> /etc/environment`

Which would need to be run on container start.


Edit 2: In theory I think we could also get away with `2 * * * * . /etc/environment; cd /var/lib/habitica && /usr/local/bin/node ./run-team-cron.js >> /var/log/cron.log 2>&1`

as long as the printenv is set on container start as well.

Edit 3: I like the Edit 2 answer better...

So on container start we stamp the environment variables

crontab can literally be
```
@reboot printenv | grep -v "no_proxy" >> /etc/environment
2 * * * * . /etc/environment; cd /var/lib/habitica && /usr/local/bin/node ./run-team-cron.js >> /var/log/cron.log 2>&1
```

Much sleeker than another in between script.

**Comment by Saik0Shinigami** [comment]
@reboot doesn't work in cron on a docker container it seems.... every day I find more reasons why I like LXC more than docker.

The dockerfile then needs to be modified to run the command on start to dump the current ENVs into a file for cron to use.

```
CMD sh -c 'printenv | grep -v "no_proxy" >> /etc/environment && /etc/init.d/cron start && node /var/lib/habitica/website/transpiled-babel/index.js'
```

with the cron modified as such

```2 * * * * . /etc/environment; cd /var/lib/habitica && /usr/local/bin/node ./run-team-cron.js >> /var/log/cron.log 2>&1```

Would be my election. This is tested working in my environment. If anyone could confirm, then changes pushed and I think we'll have group tasks working properly once and for all.

**Comment by awinterstein** [comment]
I integrated your proposed changes into the latest container build, @Saik0Shinigami.

@prabhjotsbhatia-ca, you could try with that, if you'd like.

**Comment by prabhjotsbhatia-ca** [comment]
@Saik0Shinigami @awinterstein Sorry I'm a little late to the party.  I've been looking at this from another angle. 
I'm not entirely sure what purpose the config.json file created at docker build time does, but adding it there and then reading it from the file could be another route. 
So:
 Dockerfile: 

```diff
--- a/Dockerfile
+++ b/Dockerfile
@@ -4,6 +4,9 @@ FROM node:20 AS build
 ARG CI=true
 ARG NODE_ENV=production
 
+ARG NODE_DB_URI
+ENV NODE_DB_URI=${NODE_DB_URI}
+
 RUN git config --global url."https://".insteadOf git://
 
 WORKDIR /usr/src/habitica
@@ -35,6 +38,7 @@ RUN echo '{\n\
     "INVITE_ONLY": "false",\n\
     "MAINTENANCE_MODE": "false",\n\
     "MONGODB_POOL_SIZE": "10",\n\
+    "NODE_DB_URI": "'"${NODE_DB_URI}"'",\n\
     "NODE_ENV": "production",\n\
     "PATH": "bin:node_modules/.bin:/usr/local/bin:/usr/bin:/bin",\n\
     "PORT": 3000,\n\
```

and 
docker-compose: 

```diff
--- a/docker-compose.yml
+++ b/docker-compose.yml
@@ -5,10 +5,12 @@ services:
       context: .
       dockerfile: ./Dockerfile
       target: server
+      args:
+        NODE_DB_URI: mongodb://mongo/habitica # this only needs to be adapted if using a separate database
+
     depends_on:
       - mongo
     environment:
-      - NODE_DB_URI=mongodb://mongo/habitica # this only needs to be adapted if using a separate database
       - BASE_URL=http://127.0.0.1:8080 # change this to the URL under which your instance will be reachable
       - INVITE_ONLY=false # change to `true` after registration of initial users, to restrict further registrations
     networks:
```

**Comment by awinterstein** [comment]
Yes, this would work for the default case of running a container for MongoDB with Docker compose. But it would break the option to just configure accessing any other MongoDB instance that is for example running on another host.

You can, however, make your own `config.json` available from outside the container, instead of using the environment variables.

The `config.json` that is created during the container build is used right now for the build itself (as some values need to be set) and to provide default values for all Habitica instances.

**Comment by prabhjotsbhatia-ca** [comment]
For people running their own mongo DB instance, they could change the value in the args section of the docker-compose.yml file, and running `docker-compose up` would do the trick. It would of course do a rebuild as usual. 
Perhaps I'm missing something here.

**Comment by awinterstein** [comment]
Sorry, I didn't clearly state what I meant. I was referring to running Habitica with a container that gets downloaded from Docker Hub instead of building it on my own. The way, that I described in the project readme file for setting up the hosting. In this case, I cannot change build args for Docker, because I don't build it on my own.

**Comment by prabhjotsbhatia-ca** [comment]
> Sorry, I didn't clearly state what I meant. I was referring to running Habitica with a container that gets downloaded from Docker Hub instead of building it on my own. The way, that I described in the project readme file for setting up the hosting. In this case, I cannot change build args for Docker, because I don't build it on my own.

I understand what you mean. Thanks for clearing that up! Sorry for the misunderstanding on my part.

**Comment by awinterstein** [comment]
The fix of @Saik0Shinigami works also in my deployment based on the current release. I'll close this issue then.
